@base_url = http://localhost:5001

### health check
GET {{base_url}}/

### list products
GET {{base_url}}/products

### get a product
GET {{base_url}}/products/d3b07384-d9a7-4b2a-8b0d-1e4e2b2b2b2b

### list orders
GET {{base_url}}/orders

### create a order
POST {{base_url}}/orders/d3b07384-d9a7-4b2a-8b0d-1e4e2b2b2b2b

### cancel a order
DELETE {{base_url}}/orders/a2267dd5-142e-4566-a46e-efe64c44610d

### dapr runtime status
GET http://localhost:3501/v1.0/metadata